export type SteamUiTokenSpec = { tokens?: string[]; params?: string[] };

export const GDL_STEAM_TOKEN_SPECS: Record<string, SteamUiTokenSpec> = {
	activity: { tokens: ['AppDetails_SectionTitle_Activity'] },
	post_placeholder: { tokens: ['AppActivity_StatusUpdate_Post'] },
	publish: { tokens: ['AppActivity_PostStatusUpdate'] },
	fetch_more: { tokens: ['AppActivity_FetchMore'] },
	community_content: { tokens: ['AppDetails_SectionTitle_Community'] },
	achievements_label: { tokens: ['AppDetails_SectionTitle_Achievements'] },
	achievements_unlocked: { tokens: ['AppDetails_PlayerUnlockedPercent'], params: ['unlocked', 'total'] },
	all_achievements_unlocked: { tokens: ['AppDetails_PlayerUnlockedPercentAll', 'AppDetails_PlayerUnlockedPercent'], params: ['unlocked', 'total'] },
	no_recent_activity: { tokens: ['AppActivity_NoActivity'] },
	latest_news: { tokens: ['AppActivity_ViewLatestNews'] },
	developer: { tokens: ['AppDetails_Developer'] },
	publisher: { tokens: ['AppDetails_Publisher'] },
	franchise: { tokens: ['AppDetails_Franchise'] },
	release_date: { tokens: ['AppDetails_ReleaseDate'] },
	game_information: { tokens: ['AppDetails_GameInfo'] },
	show_game_details: { tokens: ['GameAction_ViewDetails'] },
	hide_game_details: { tokens: ['GameAction_ViewDetails_Collapse'] },
	single_player: { tokens: ['AppDetails_Feature_SinglePlayer'] },
	multi_player: { tokens: ['AppDetails_Feature_MultiPlayer'] },
	cooperative: { tokens: ['AppDetails_Feature_CoOp'] },
	cloud_saves: { tokens: ['AppDetails_Feature_SteamCloud'] },
	full_controller: { tokens: ['AppDetails_Feature_FullController'] },
	partial_controller: { tokens: ['AppDetails_Feature_PartialController'] },
	controller_ps4: { tokens: ['AppDetails_Feature_PS4'] },
	controller_ps5: { tokens: ['AppDetails_Feature_PS5'] },
	family_sharing: { tokens: ['AppDetails_Feature_FamilySharing'] },
	trading_cards: { tokens: ['AppDetails_SectionTitle_TradingCards'] },
	feed_game_launch: { tokens: ['EventDisplay_EventType_10'] },
	feed_game_update: { tokens: ['AppActivity_EventType_GameUpdate'] },
	feed_major_update: { tokens: ['MajorUpdate_Type14'] },
	feed_dlc: { tokens: ['EventDisplay_EventType_15'] },
	feed_offer: { tokens: ['EventDisplay_EventType_20'] },
	feed_event: { tokens: ['EventDisplay_EventType_22'] },
	feed_news: { tokens: ['EventDisplay_EventType_28'] },
	feed_beta: { tokens: ['EventDisplay_EventType_29'] },
	feed_content: { tokens: ['EventDisplay_EventType_30'] },
	feed_free_trial: { tokens: ['EventDisplay_EventType_31'] },
	feed_season: { tokens: ['EventDisplay_EventType_32'] },
	feed_community: { tokens: ['EventDisplay_EventType_Other'] },
	locked_achievements: { tokens: ['AppDetails_LockedAchievements', 'Achievement_Filter_Locked'] },
	view_all_achievements: { tokens: ['AppDetails_Achievement_ViewAllAchievements', 'AppDetails_ViewAllAchievements', 'AppDetails_Achievements_ViewAll'] },
	view_dlc_store: { tokens: ['AppDetails_ViewDLCInStore', 'AppDetails_DLC_ViewInStore'] },
	view_my_cards: { tokens: ['AppDetails_TradingCards_ViewMyCards'] },
	store_page: { tokens: ['AppDetails_Links_Store', 'AppDetails_Link_Store', 'AppDetails_StorePage'] },
	dlc_links: { tokens: ['AppDetails_Links_DLC', 'AppDetails_SectionTitle_DLC', 'AppProperties_DLCPage'] },
	community_hub: { tokens: ['AppDetails_Links_Community', 'AppDetails_Link_GameHub', 'AppDetails_Links_CommunityHub'] },
	points_shop: { tokens: ['AppDetails_Links_PointsShop', 'Menu_PointsShop', 'PointsShop_Title'] },
	discussions: { tokens: ['AppDetails_Link_Discussions', 'Menu_Discussions', 'AppDetails_SectionTitle_Discussions'] },
	guides: { tokens: ['AppDetails_Link_Guides', 'AppOverlay_Guides', 'AppDetails_SectionTitle_Guides'] },
	workshop: { tokens: ['AppDetails_Link_Workshop', 'Menu_Workshop', 'AppDetails_SectionTitle_Workshop', 'AppDetails_Feature_SteamWorkshop'] },
	support: { tokens: ['AppDetails_Link_Support', 'SupportLink_Label', 'AppDetails_Soundtrack_Support'] },
	friends_recently_played_single: { tokens: ['AppDetails_Friends_PlayedRecently_Single', 'AppDetails_Friends_PlayedRecently'] },
	friends_recently_played: { tokens: ['AppDetails_Friends_PlayedRecently'], params: ['count'] },
	friends_previously_played_single: { tokens: ['AppDetails_Friends_PlayedPreviously_Single', 'AppDetails_Friends_PlayedPreviously'] },
	friends_previously_played: { tokens: ['AppDetails_Friends_PlayedPreviously'], params: ['count'] },
	friends_who_play_single: { tokens: ['AppDetails_Friends_Who_Play_Single', 'AppDetails_Friends_Who_Play', 'AppDetails_SectionTitle_Friends'] },
	friends_who_play: { tokens: ['AppDetails_Friends_Who_Play', 'AppDetails_SectionTitle_Friends'], params: ['count'] },
	friends_wishlisted_single: { tokens: ['AppDetails_Friends_Wishlist_Single', 'AppDetails_Friends_WishlistSingle', 'AppDetails_Friends_OnWishlist', 'AppDetails_Friends_Wishlist'], params: ['game'] },
	friends_wishlisted_plural: { tokens: ['AppDetails_Friends_Wishlist_Plural', 'AppDetails_Friends_WishlistPlural', 'AppDetails_Friends_OnWishlist_Plural', 'AppDetails_Friends_Wishlist'], params: ['count', 'game'] },
	show_all_wishlisted: { tokens: ['AppDetails_Friends_ShowAllWishlisted', 'AppDetails_Friends_ShowAllWishlist'], params: ['count'] },
	view_all_friends: { tokens: ['AppDetails_Friends_ViewAll', 'AppDetails_ViewAllFriendsWhoPlay'] },
	close: { tokens: ['Button_Close', 'Modal_Close'] },
	cancel: { tokens: ['Button_Cancel'] },
	continue: { tokens: ['Button_Continue'] },
	search: { tokens: ['Search'] },
	save: { tokens: ['Button_Save', 'Save'] },
	playtime_hours: { tokens: ['AppDetails_Playtime_Hours', 'Time_Hours_Abbreviated'], params: ['count'] },
	playtime_minutes: { tokens: ['AppDetails_Playtime_Minutes', 'Time_Minutes_Abbreviated'], params: ['count'] },
	playtime_less_than_minute: { tokens: ['AppDetails_Playtime_LessThanMinute'] },
	playtime_section_title: { tokens: ['AppDetails_SectionTitle_Playtime'] },
	last_played_section_title: { tokens: ['AppDetails_SectionTitle_LastPlayed', 'AppDetails_SectionTitle_LastSession'] },
	last_played_today: { tokens: ['DateTime_Today', 'Date_Today', 'AppActivity_Today'] },
	last_played_yesterday: { tokens: ['DateTime_Yesterday', 'Date_Yesterday', 'AppActivity_Yesterday'] },
	last_played_days_ago: { tokens: ['DateTime_DaysAgo'], params: ['count'] },
	hidden_achievement: { tokens: ['Achievement_Hidden'] },
	no_achievements: { tokens: ['AppDetails_NoAchievements', 'Achievement_Filter_None', 'AppOverview_NoAchievements'] },
};

export const STEAM_LANGUAGE_TO_LOCALE: Record<string, string> = {
	english: 'en-US', german: 'de-DE', french: 'fr-FR', italian: 'it-IT', koreana: 'ko-KR',
	spanish: 'es-ES', latam: 'es-419', schinese: 'zh-CN', tchinese: 'zh-TW', russian: 'ru-RU',
	thai: 'th-TH', japanese: 'ja-JP', portuguese: 'pt-PT', brazilian: 'pt-BR', polish: 'pl-PL',
	danish: 'da-DK', dutch: 'nl-NL', finnish: 'fi-FI', norwegian: 'nb-NO', swedish: 'sv-SE',
	hungarian: 'hu-HU', czech: 'cs-CZ', romanian: 'ro-RO', turkish: 'tr-TR', arabic: 'ar-SA',
	bulgarian: 'bg-BG', greek: 'el-GR', ukrainian: 'uk-UA', vietnamese: 'vi-VN', indonesian: 'id-ID', malay: 'ms-MY',
};
