export const SPANISH_TOKEN_FALLBACKS: Record<string, string> = {
	AppDetails_Shortcut_Explanation: 'Alguna información sobre %1$s no está disponible porque no es un juego de Steam o es un mod. No obstante, Steam controla el inicio del juego por ti y, en la mayoría de los casos, la interfaz dentro del juego estará disponible.',
	AppDetails_SectionTitle_Activity: 'Actividad',
	AppActivity_StatusUpdate_Post: 'Diles algo sobre este juego a tus amigos...',
	AppActivity_PostStatusUpdate: 'Publicar',
	AppActivity_FetchMore: 'Cargar más actividad',
	AppDetails_SectionTitle_Community: 'Contenido de la comunidad',
	AppDetails_SectionTitle_Achievements: 'Logros',
	AppActivity_NoActivity: 'No hay actividad reciente de los desarrolladores de este título o de tus amigos.',
	AppActivity_ViewLatestNews: 'Ver las últimas novedades',
	AppDetails_Developer: 'Desarrollador',
	AppDetails_Publisher: 'Editor',
	AppDetails_Franchise: 'Franquicia',
	AppDetails_ReleaseDate: 'Fecha de publicación',
	AppDetails_GameInfo: 'Información del juego',
	GameAction_ViewDetails: 'Mostrar detalles del juego',
	GameAction_ViewDetails_Collapse: 'Ocultar detalles del juego',
	AppDetails_Feature_SinglePlayer: 'Un jugador',
	AppDetails_Feature_MultiPlayer: 'Multijugador',
	AppDetails_Feature_CoOp: 'Cooperativo',
	AppDetails_Feature_SteamCloud: 'Progreso guardado en la nube',
	AppDetails_Feature_FullController: 'Compatibilidad total con control',
	AppDetails_Feature_PartialController: 'Compatibilidad parcial con control',
	AppDetails_Feature_FamilySharing: 'Préstamo familiar',
	AppDetails_Feature_RemotePlayTogether: 'Remote Play Together',
	AppDetails_SectionTitle_TradingCards: 'Tarjetas',
	AppDetails_Links_Store: 'Página de la tienda',
	AppDetails_Links_DLC: 'DLC',
	AppDetails_Links_Community: 'Punto de encuentro',
	AppDetails_Links_PointsShop: 'Tienda de puntos',
	AppDetails_Link_Discussions: 'Discusiones',
	AppDetails_Link_Guides: 'Guías',
	AppDetails_Link_Workshop: 'Steam Workshop',
	AppDetails_Link_Support: 'Soporte',
	Button_Close: 'Cerrar',
	Button_Cancel: 'Cancelar',
	Button_Continue: 'Continuar',
	Search: 'Buscar',
	Button_Save: 'Guardar',
	AppActivity_Achieved: ' ha conseguido',
	AppActivity_PostedVideo: ' ha compartido un vídeo',
	AppActivity_PostedVideo_Plural: ' ha compartido %1$s vídeos',
	AppActivity_PostedScreenshot: ' ha compartido una captura de pantalla',
	AppActivity_PostedScreenshot_Plural: ' ha compartido %1$s capturas de pantalla',
	AppActivity_RecommendedGame: ' ha hecho una reseña de este juego',
	AppActivity_RecommendedGame_ReadMore: 'Leer más',
	AppActivity_ReceivedNewGameList: ' ha añadido %1$s a su biblioteca',
	AppActivity_AddedGameToWishlist: ' ha añadido %1$s a su %2$s',
	AppActivity_Wishlist: 'lista de deseados',
	AppActivity_PlayedGameFirstTime: ' ha jugado a %1$s por primera vez',
	AppActivity_UserStatus: ' ha publicado una actualización de estado',
	AppDetails_SectionTitle_Controller: 'Control',
	AppDetailsControllerSection_Title_Supported_Xbox: 'Compatible con tu control de Xbox',
	AppDetailsControllerSection_Title_Supported_DualShock: 'Compatible con tu control DualShock',
	AppDetailsControllerSection_Title_Supported_Dualsense: 'Compatible con tu control DualSense',
	AppDetailsControllerSection_Title_Supported_Generic: 'Compatible con tu control',
	AppDetailsControllerSection_DevSupported: 'Este juego debería funcionar muy bien con tu control',
	AppControllerConfiguration_Link: 'Ver los ajustes del control',
	AppDetails_SectionTitle_Friends: 'Amigos que juegan',
	AppDetails_Friends_Who_Play: 'Amigos que juegan',
	AppDetails_Friends_PlayedPreviously: '%1$s amigos lo jugaron antes',
	AppDetails_Friends_PlayedPreviously_Single: '1 amigo lo jugó antes',
	AppDetails_Friends_PlayedRecently: '%1$s amigos jugaron recientemente',
	AppDetails_Friends_PlayedRecently_Single: '1 amigo jugó recientemente',
	AppDetails_Friends_Wishlist_Single: '1 amigo tiene %1$s en su lista de deseados',
	AppDetails_Friends_Wishlist_Plural: '%1$s amigos tienen %2$s en su lista de deseados',
	AppDetails_Friends_Wishlist: '%1$s amigos tienen %2$s en su lista de deseados',
	AppDetails_Friends_ViewAll: 'Ver todos los amigos que lo juegan',
	AppDetails_ViewAllFriendsWhoPlay: 'Ver todos los amigos que lo juegan',
	AppDetails_Achievement_ViewAllAchievements: 'Ver todos mis logros',
	AppDetails_ViewAllAchievements: 'Ver todos mis logros',
	AppDetails_Achievements_ViewAll: 'Ver todos mis logros',
	Keyboard_Title: 'Teclado',
};

